name: ðŸ§ Repo Analyzer

on:
  workflow_dispatch:
  # Run job every day at 1:00pm
  # schedule:
  #             # https://crontab.guru/
  #             #   â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ minute (0 - 59)
  #             # â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ hour (0 - 23)
  #             # â”‚ â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ day of the month (1 - 31)
  #             # â”‚ â”‚ â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ month (1 - 12 or JAN-DEC)
  #             # â”‚ â”‚ â”‚ â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ day of the week (0 - 6 or SUN-SAT)
  #             # â”‚ â”‚ â”‚ â”‚ â”‚
  #             # â”‚ â”‚ â”‚ â”‚ â”‚
  #             # â”‚ â”‚ â”‚ â”‚ â”‚
  #             # * * * * *
  #   - cron:  '0 13 * * *'

jobs:
  execute_analyzer:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: âš¡ï¸ Invoke Repo Analyzer Function Lambda
        id: lambdaInvocation
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: ${{ github.event.repository.name }}-prod-fetchAnalyzeRepoQueue
          # Payload: '{ "myParameter": false }'

      - name: ðŸ“ Store response payload to file
        if: always()
        run: echo '${{ fromJSON(steps.lambdaInvocation.outputs.response).Payload }}' > invocation-response.json

      - name: â¬†ï¸ Upload Lambda output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lambda-output
          path: invocation-response.json

      - name: âœ‚ï¸ Extract repository URL from previous step
        if: always()
        run: echo ::set-output name=repoUrl::$(cat invocation-response.json | jq . | jq .body.repoUrl | tr -d '"' 2>&1)
        id: lambdaOutputExtraction

      - name: â¬‡ï¸ Checkout external repository
        uses: actions/checkout@v3
        with:
          repository: ${{ steps.lambdaOutputExtraction.outputs.repoUrl }}

      # preform code scan
      # https://github.com/marketplace/actions/codacy-analysis-cli
      - name: âœ… Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master

      - name: ðŸ“ Check README file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "README.md"

      # preform TYPO scan
      # https://github.com/crate-ci/typos
      - name: ðŸš« Check spelling of README
        if: steps.check_files.outputs.files_exists == 'true'
        uses: crate-ci/typos@master
        with: 
          files: ./README.md

      - name: âœï¸ Generate analysis report
        run: |
          mkdir output
          cd output
          cat > metadata.txt
          echo ${{ steps.lambdaOutputExtraction.outputs.repoUrl }} >> metadata.txt
          date >> metadata.txt
          cat > report.md
          echo '## ${{ steps.lambdaOutputExtraction.outputs.repoUrl }}' >> report.md

      - name: ðŸšš Push report to store repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          source-directory: output
          destination-github-username: spencerlepine
          destination-repository-name: ${{ secrets.CONTRIBUTION_STORE_REPO }}
          target-directory: ${{ steps.lambdaOutputExtraction.outputs.repoUrl }}
          user-email: spencerlepine26@gmail.com
          target-branch: main
